### ISSUE TITLE
Missing scala unit tests using docker image

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-runtime-go#12]
The repo should have a series of tests that use `docker run` and then invoke a series of basic actions both using source and pre-compile zip

Similar as other tests in runtime repos:
https://github.com/apache/incubator-openwhisk-runtime-swift/tree/master/tests/src/test/scala/runtime/actionContainers

**Comment by csantanapr** [comment]
@sciabarracom pointed me to the scala tests in the core/main repo PR.
The tests should live in this repo instead. https://github.com/apache/incubator-openwhisk/pull/3564

**Comment by sciabarracom** [comment]
added in PR#45

**Comment by sciabarracom** [comment]
All the tests are there now, please close

**Comment by csantanapr** [comment]
This is fixed now
