### ISSUE TITLE
Add scala integration tests

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-runtime-go#13]
It would be good to add some integration tests that go actions are invoke thru the whisk controller.
A new kind should be use when deploying and setup in Travis similar to other runtime repos
https://github.com/apache/incubator-openwhisk-runtime-swift/tree/master/ansible/environments/local

**Comment by sciabarra** [comment]
I provided the tests in a PR for apache/incubator-openwhisk so you can close this

**Comment by sciabarracom** [comment]
working on this right now

**Comment by sciabarracom** [comment]
added in PR#45

**Comment by sciabarracom** [comment]
Tests are there and all the mandatory tests passing. Please close

**Comment by csantanapr** [comment]
we have the conformance test passing in Travis now
