### ISSUE TITLE
replace github.com/sciabarracom

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-runtime-go#15]
Several references to `sciabarracom` github user/org
like `build.gradle` has `github.com/sciabarracom/incubator-openwhisk-runtime-go`

Should be replace with `github.com/apache`

**Comment by sciabarra** [comment]
now that the code is available in github under apache you can do it

**Comment by csantanapr** [comment]
Thanks @sciabarra for looking into this one.
