### ISSUE TITLE
 FAIL: Example_badinit_nocompiler 

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-runtime-go#23]
Build in travis is failing
https://travis-ci.org/apache/incubator-openwhisk-runtime-go/builds/373762183#L1197
```
--- FAIL: Example_badinit_nocompiler (1.11s)
got:
400 {"error":"no action defined yet"}
200 {"ok":true}
400 {"error":"cannot start action: command exited"}
400 {"error":"cannot start action: command exited"}
200 {"ok":true}
400 {"error":"command exited"}
want:
400 {"error":"no action defined yet"}
200 {"ok":true}
400 {"error":"cannot start action: command exited"}
400 {"error":"cannot start action: command exited"}
400 {"error":"cannot start action: command exited"}
400 {"error":"no action defined yet"}
=== RUN   Example_bininit_nocompiler
```

Same test passed when it was from the PR
https://travis-ci.org/apache/incubator-openwhisk-runtime-go/builds/373761010#L1208

**Comment by csantanapr** [comment]
@sciabarracom could you take a look why this test is failing.

**Comment by csantanapr** [comment]
@sciabarra you have an update on this?

**Comment by sciabarracom** [comment]
Can I get a debug build? Will contact you on slack, you start the build I’m debug and give me ssh to connect to the temporary container.

**Comment by csantanapr** [comment]
It looks like the test is passing in travis now.
Closing...
