### ISSUE TITLE
Pin go dependencies

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-runtime-go#24]
We need to list and pin all the go dependencies. 
With this we need to document their respective dependencies for Apache  Software Foundation 
 
This also helps a bit for stability

**Comment by csantanapr** [comment]
Could you look into this @sciabarra ?

I think is a matter of declaring them in build.gradle for gogradle to download them like the go CLI repo

**Comment by sciabarracom** [comment]
Ok accepted

**Comment by csantanapr** [comment]
Close by #30
