### ISSUE TITLE
Update Apache license with third party content

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-runtime-go#25]
We need to include in the License all 3rd party dependencies

Some would be hard dependencies source that we compiled into final compiled artifact.
Some would be we depend on like test frameworks, or go runtime.
These licenses would also need to be included in the repo

See the runtime-nodejs as an example:
https://github.com/apache/incubator-openwhisk-runtime-nodejs/blob/master/LICENSE.txt
https://github.com/apache/incubator-openwhisk-runtime-nodejs/tree/master/licenses

cc @houshengbo @sciabarracom

**Comment by sciabarracom** [comment]
Ok

**Comment by csantanapr** [comment]
Close by #30
