### ISSUE TITLE
proxy doesn't handle unicode conformance for OpenWhisk.

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-runtime-go#41]
the proxy should be able to handle input JSON and output if it wants the same exact JSON output.

Currently it returns nil for unicode input
```bash
wsk action invoke golangfunc -p winter "❄ ☃ ❄" -r
```
The expected output should be:
```json
{
"winter": "❄ ☃ ❄"
}
```
But the output is not is nil
```json
{
"winter": nil
}
```

cc @sciabarra

**Comment by csantanapr** [comment]
cc @rabbah

**Comment by sciabarracom** [comment]
I am going to try to debug this.

**Comment by sciabarracom** [comment]
Just tried with my (updated) command line test suite (ses PR #43) and works for me:

```
$ docker pull openwhisk/actionloop-golang-v1.10:master
Digest: sha256:f6dbc20ec87ac8c82ca1600ea6b55756dfe5e9e4d809f3872890310c3216e5ac
$ ./start.sh openwhisk/actionloop-golang-v1.10:master
2a3b778c9372fa1cde998c7d096ba0e543931557edb62cf0db0bb97401026a4b
$  bin/init.sh etc/hello.go 
{"ok":true}
$ bin/run.sh '{"name": "❄ ☃ ❄"}'
{"hello":"Hello, ❄ ☃ ❄!"}
200
```

Can you point me to the test failing?

Note I am using the image

**Comment by sciabarracom** [comment]
New version should work, please confirm and close

**Comment by csantanapr** [comment]
we have conformance test passing with unicode 
https://github.com/apache/incubator-openwhisk-runtime-go/blob/master/tests/src/test/scala/runtime/actionContainers/ActionLoopBasicGoTests.scala#L74
