### ISSUE TITLE
Travis failing to deploy nightly image

### ISSUE THREAD

**Issue by csantanapr** [apache/incubator-openwhisk-runtime-go#74]
+TERM=dumb
+./gradlew :actionProxyLoop:distDocker -PdockerRegistry=docker.io -PdockerImagePrefix=openwhisk -PdockerImageTag=latest
Found go 1.11.5 in /home/travis/.gimme/versions/go1.11.5.linux.amd64/bin/go, use it.
FAILURE: Build failed with an exception.
* What went wrong:
Project 'actionProxyLoop' not found in root project 'runtime-golang'.
https://travis-ci.org/apache/incubator-openwhisk-runtime-go/builds/507877207#L2058

**Comment by sciabarra** [comment]
is still an open issue?
