### ISSUE TITLE
The openwhisk/actionloop-v2 includes the dynamic executable

### ISSUE THREAD

**Issue by sciabarracom** [apache/incubator-openwhisk-runtime-go#80]
The build.gradle uses the "-static" but the image published on Docker Hub as "actionloop-v2" is still dymanically linked

```
docker run --entrypoint=ldd openwhisk/actionloop-v2  /bin/proxy
	linux-vdso.so.1 =>  (0x00007ffc35f65000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8e4aee2000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8e4ab18000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8e4b0ff000)
```

Note that if I rebuild the runtime locally it is statically linked:

```
docker run --entrypoint=ldd whisk/actionloop-v2  /bin/proxy
	not a dynamic executable
```

**Comment by sciabarracom** [comment]
Current version (tag from docker hub taken now) is still a DLL 

docker run --entrypoint=ldd openwhisk/actionloop-v2:ddd3299  /bin/proxy

**Comment by sciabarracom** [comment]
Note in build.gradle there is:
 go """build -o common/proxy -ldflags '-extldflags "-static"'  main/proxy.go"""

**Comment by rabbah** [comment]
What if you build with go? If the gradle built disappeared I’m not sure who’d miss it.

**Comment by sciabarracom** [comment]
First it is still built with go, just wrapped by grade, and second there are the scala tests so gradle or something similar is still built. I think the problem is only in the configuration of Travis/DockerHub because it builds properly with gradle it is just the right image does not reach docker hub

-- 
 Michele Sciabarra
 michele@sciabarra.com



----- Original message -----

**Comment by lolgab** [comment]
The issue seems to remain unsolved. `/bin/proxy` is dynamically linked in `openwhisk/actionloop-v2:latest` on docker hub.

**Comment by sciabarracom** [comment]
Can you please point to the docker image you are talking about? All the newer version of the docker images are build straight from the sources so it is no more an issue.

**Comment by lolgab** [comment]
This is the image i'm running: https://hub.docker.com/layers/openwhisk/actionloop-v2/latest/images/sha256-d4b6cd4b434a59d6850d068c7511b977fa2d0404be62e1edc4cfdfe1ab800cc5

**Comment by sciabarracom** [comment]
The docker image is the "standalone" actionloop-v2 that is now obsolete. You are supposed to be using one of the runtime images like golang, python, ruby etc that now builds the proxy from sources (after the de-incubation)

**Comment by lolgab** [comment]
Yes, I was trying to build a runtime for [Scala Native](scala-native.org).
So I will follow the same steps done by the other runtimes to build the proxy from sources.
Thank you for your answers :)

**Comment by lolgab** [comment]
I tried right now with the `openwhisk/actionloop-v2:nightly` and it has `/bin/proxy` statically linked 👍

**Comment by sciabarracom** [comment]
I think the issue really is: update the sample in the toolkit to use sources.... We are now tagging sources in order to use a released version.

**Comment by sciabarracom** [comment]
As a side note, yes actually there was a change to use the tag nightly instead of latest... so also this can be confusing.
