### ISSUE TITLE
license for stretcher/testify

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk-runtime-go#91]
this commit removed references to `stretecher/testify`'s license but there are still references to this go module https://github.com/apache/incubator-openwhisk-runtime-go/commit/ddd329946c1d061f256a274d6ccd23e527760e06#diff-61e0bdf7e1b43c5c93d9488b22e04170

https://github.com/apache/incubator-openwhisk-runtime-go/blob/1cbb96383502ca6df45058d966927c0796c31fbd/go.mod#L5

https://github.com/apache/incubator-openwhisk-runtime-go/blob/1cbb96383502ca6df45058d966927c0796c31fbd/openwhisk/actionProxy_test.go#L28

(there are others.)

**Comment by rabbah** [comment]
Per https://github.com/apache/incubator-openwhisk-runtime-go/commit/ddd329946c1d061f256a274d6ccd23e527760e06?email_source=notifications&email_token=ABF25MSUK4EAGJ726O473LTPZU5GPA5CNFSM4HWJKCG2YY3PNVWWK3TUL52HS4DFVVBW63LNNF2EG33NNVSW45FKMNXW23LFNZ2F62LEZYBAJQ33#commitcomment-33866619 we need to add the license link back.

**Comment by mrutkows** [comment]
fixing in https://github.com/apache/incubator-openwhisk-runtime-go/pull/92
